"""Create contatos and agendamentos tables

Revision ID: db9ed06a755c
Revises: 
Create Date: 2025-04-21 23:18:01.173922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db9ed06a755c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamentos', 'contato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agendamentos', 'horario_envio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contatos', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contatos', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('contatos_telefone_key', 'contatos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contatos_telefone_key', 'contatos', ['telefone'])
    op.alter_column('contatos', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contatos', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agendamentos', 'horario_envio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agendamentos', 'contato_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
